version: "3.8"

services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./db-data:/var/lib/mysql

    redis:
        image: redis:7.0
        ports:
            - "6379:6379"
        volumes:
            - ./cache:/data
